language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

after_deploy:
  - echo "done deploying"
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "weoweyou"
  env: "Weoweyou-env"
  bucket_name: "elasticbeanstalk-us-east-2-503109812026"
  bucket_path: "weoweyou"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
